config/routes.rb
Rails.application.routes.draw do
 
  root 'departments#index'
  
  resources :departments do
    resources :items
  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :destroy, :update] 
  
  def index
    @departments = Department.all
  end

  def show
    
  end

  def new
    @department = Department.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else 
      render :edit
    end
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end 

  def destroy
    @department.destroy
    redirect_to departments_path
  end 

  private

  def department_params
    params.require(:department).permit(:name)
  end 

  def set_department
    @department = Department.find(params[:id])
  end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :destroy, :edit, :update]
  
  def index
    @items = @department.items
  end

  def new
    @item = @department.items.new
    render partial: 'form'
  end

  def show
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to [@department, @item]
    else
      render :new
    end 
  end  

  def edit
    render partial: 'form'
  end

  def update
    if @item.update(item_params)
      redirect_to [@department, @item]
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path(@department)
  end

  private 

  def set_department
    @department = Department.find(params[:department_id]) 
  end 

  def set_item 
    @item = Item.find(params[:id])
  end 

  def item_params
    params.require(:item).permit(:name, :description)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1>New Department</h1>

<%= form_for @department do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

<%= link_to 'Back', root_path %>

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<nav class = "blue">
    <ul>
    <li><a href="#">All Department Stores</a></li>
    <li><a href="#">Mall Info</a></li>
    <li><a href="#">Contact Us</a></li>
    </ul>
</nav>

<h1 class="center">All Departments</h1>

<div class="container">
    <div class="card z-depth-4 center">
        <div class="center">
        <div class="container">
                <br>
                <a> <%= link_to 'Create New Department', new_department_path %></a>
                <div style='width: 105px; display:inline-block'></div>
                <a class="btn-floating yellow darken-4" href="#">
                    <i class="material-icons">add</i>
                </a>
                <br>
                <br>
                <hr/>
                <% @departments.each do |department|%>
                <div style="min-height: 50px">
                    <p class="left"><%= link_to department.name, department %> </p>
                    <a class="btn-floating blue darken-4 right" style="postion: relative; top: 10px" href="#">
                        <i class="material-icons">pageview</i>
                    </a>
                <hr/>
             
            </div>
            <% end %>
               <br>
            </div>
         <div>
    </div>
</div>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<nav class = "blue">
    <ul>
    <li><a href="#">All Department Stores</a></li>
    <li><a href="#">Mall Info</a></li>
    <li><a href="#">Contact Us</a></li>
    </ul>
</nav>

<h1 class="center"><%= @department.name %> </h1>
<div class="container">
    <div class="card z-depth-5">
        <div class="center">
        <div class="card-content">
            <span class="card-title">Would you like to... </span>
            <br>
            <br>
            <p><%= link_to 'View Items', department_items_path(@department) %></p>
            <br>
            <br>
            <div class="card-action">
            <%= link_to 'Edit Department', edit_department_path(@department) %>
            <%= link_to 'Delete Department', @department, method: :delete %>
            <%= link_to 'Back to Departments List', root_path %>
            </div>
        </div>
        </div>
    </div>
</div>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@department, @item] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<nav class = "blue">
    <ul>
    <li><a href="#">All Department Stores</a></li>
    <li><a href="#">Mall Info</a></li>
    <li><a href="#">Contact Us</a></li>
    </ul>
</nav>

<h1 class="center">Click an Item To View Content</h1>


<div class= "row">
  <div class="center">
    <div class='container'>
      <div class="card z-depth-3">
      <div class="card-title">
        <%= link_to 'Create New Item', new_department_item_path(@department) %>
        <br>
        <hr/>
      </div>
        <ul class="container">
          <% @items.each do |item| %>
            <li><%= link_to item.name, [@department, item] %></li>
            <hr/>
          <% end %>
        </ul>

        <%= link_to @department.name, @department%>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<nav class = "blue">
    <ul>
    <li><a href="#">All Department Stores</a></li>
    <li><a href="#">Mall Info</a></li>
    <li><a href="#">Contact Us</a></li>
    </ul>
</nav>

<h1 class="center"><%= @department.name %> - <%= @item.name %></h1>
<hr/>

<div class="container">
<div class="center">
    <div class="col s12 m6">
      <div class="card darken-1">
        <div class="card-content blue-text">
          <span class="card-title center"><%= @item.name %></span>
          <p class="center"><%= @item.description %></p>
        </div>
        <div class="card-action center">
        <%= link_to 'Edit Item', edit_department_item_path([@department, @item]) %>
        <%= link_to 'Delete Item', [@department, @item], method: :delete %>
        <%= link_to 'Back To Items', department_items_path(@department) %>
        </div>
      </div>
    </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material\Icons" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>